### ISSUE TITLE
Update SQLite to 3.45 for Drupal 11

### ISSUE THREAD

**Issue by MatthieuScarset** [lando/drupal#119]
Trying to install a new Drupal 11 site with the `drupal11` lando recipe does not work because of the minimum version requirement for `sqlite` database, as shown in the error message below:

![image](https://github.com/user-attachments/assets/9e64175f-6a21-46a2-bada-9ade7f4a46d9)

Either update the sqlite version in the recipe or document the method to specify a version manually (in the `.lando.yml` file ?)

**Comment by AaronFeledy** [comment]
This is happening when choosing SQLite during installation or is it always failing?

**Comment by MatthieuScarset** [comment]
Not sure I understand the question sorry. 

This is happening when trying to install Drupal on a fresh drupal 11 lando env.

**Comment by AaronFeledy** [comment]
I was wondering if all users were seeing this error or only those trying to install Drupal on SQLite were seeing it. I was able to confirm that MySQL worked fine for but SQLite did produce the error you described, so I think I answered my question.

**Comment by UB-EW-JordiGuilleumes-proves** [comment]
I have tried to install Drupal 11 following https://www.drupal.org/download, and had similar response:
![captura-error-sqlite-drupal11](https://github.com/user-attachments/assets/7de91338-0e03-48ba-875b-2afbf6556b3a)
I use PHP 8.3.0 (also have tried PHP 8.3.8, with the same response).
