### ISSUE TITLE
D8 & D9 lando recipes fail with compser error on MacOS 12.2.1 on Lando 3.6.0

### ISSUE THREAD

**Issue by erutan** [lando/drupal#12]
I hadn't spun up a local instance recently and was running Lando 3.4.3. Upgraded to 3.6.0, rebuilt the app, destroyed the app, uninstalled lando and docker, reinstalled, tried using a blank default recipe after trimming my customized one down. Running a Drupal 9.3.6 site. Docker Desktop Version 3.6.0 (3.6.0.5487)

The first time I run `lando start` it runs properly, after that I get a warning that the composer step failed due to autload.php. The local dev site gives me the following message:

```
Warning: require(/app/vendor/composer/../laminas/laminas-zendframework-bridge/src/autoload.php): failed to open stream: No such file or directory in /app/vendor/composer/autoload_real.php on line 75 Fatal error: require(): Failed opening required '/app/vendor/composer/../laminas/laminas-zendframework-bridge/src/autoload.php' (include_path='/app/vendor/pear/archive_tar:/app/vendor/pear/console_getopt:/app/vendor/pear/pear-core-minimal/src:/app/vendor/pear/pear_exception:.:/usr/local/lib/php') in /app/vendor/composer/autoload_real.php on line 75 
```

The launchpass link for signing up in slack is also non-functional.

**Comment by labboy0276** [comment]
@erutan you most likely need to purge your containers.  Use this bash script to to get the job done: https://gist.github.com/labboy0276/4406db072f9ed3bf3641f57c1d902027

**Comment by erutan** [comment]
@labboy0276 - I ran ‘lando destroy’, deleted the containers from docker desktop, uninstalled docker desktop and related files (via appcleaner), and then ran the script from docs to remove all lando containers, but I’ll give that a try tomorrow.

**Comment by gitressa** [comment]
I use similar commands, as seen in [Cleaning up Lando containers](https://colorfield.be/blog/cleaning-lando-containers) to nuke everything, when I need a fresh start.

Thanks for sharing your script @labboy0276. Is it worth considering adding it to Lando as an option, something like this?

```
lando destroy --purge-docker-lando-cache
```

**Comment by erutan** [comment]
@labboy0276 running your script didn't fix the issue - the only change from following https://docs.lando.dev/getting-started/uninstalling.html#macos would be the docker network pruning. Nuked docker desktop and reinstalled lando again, pulled down new bitnami images as part of the `lando start` process etc.

Interestingly the issue doesn't show up when start/stopping lando anymore, but it's still present when visiting the site. I'm not sure where the `/app/ `directory is coming from before `/vendor/composer` - it's not present on my local machine or the dev server where the codebase lives or mentioned in `lando.yml` unless it's in the container itself.

**Comment by erutan** [comment]
@labboy0276 I'm out of things to try at this point. Just creating a Drupal 9 lando instance in a blank dir leaves me with a functional composer heh. I guess I can try a new Drupal install based off my `composer.json` and then move over custom files.

The launchpass slack link worked in another browser, the redirect got caught up in plugins on my main one.

**Comment by erutan** [comment]
I did a manual install of composer 2.2.7 in my local dir where the problematic Lando instance is/has been rebuilt many times:

```
lando php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
lando php composer-setup.php
```

It runs and I can interact with the directory by calling it directly:

`lando php composer.phar update` 

`lando composer` no longer crashes, but I just get a generic error on my D9 site now:

 `The website encountered an unexpected error. Please try again later.` :/

**Comment by erutan** [comment]
Adding verbose output to `settings.php` gives me something more useful and is more in line with what I might expect moving a codebase across two environments and running upgrades on it (permissions issue on local settings.php preventing db credentials from updating, I've mostly been just working by SSHing into a dev server using VS Code as it's faster than localdev, and waited on upgrading to D9 for a while waiting for some contrib to catch up).  I've fixed it and have a working local site, but...

1) The original composer autoload fail happened on both drupal8 and drupal9 recipes (I tried switching them around and rebuilding etc with no effect, I just kept the d8 one on after upgrading as it still worked well enough.

2) Composer still required a local install workaround.

Slack suggested it might have been a package requiring a more recent version of composer and it failing - perhaps time to bump things up from 2.0.7?

```
The website encountered an unexpected error. Please try again later.
Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'drupal8'@'172.21.0.3' (using password: YES) in Drupal\Core\Database\Driver\mysql\Connection::open() (line 197 of /app/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php).

Drupal\Core\Database\Driver\mysql\Connection::open(Array) (Line: 387)
Drupal\Core\Database\Database::openConnection('default', 'default') (Line: 169)
Drupal\Core\Database\Database::getConnection('default')
call_user_func_array('Drupal\Core\Database\Database::getConnection', Array) (Line: 79)
Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database') (Line: 176)
Drupal\Component\DependencyInjection\Container->get('database', 1) (Line: 212)
Drupal\Component\DependencyInjection\PhpArray
Container->resolveServicesAndParameters(Array) (Line: 62)
Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container') (Line: 176)
Drupal\Component\DependencyInjection\Container->get('cache.container') (Line: 549)
Drupal\Core\DrupalKernel->getCachedContainerDefinition() (Line: 894)
Drupal\Core\DrupalKernel->initializeContainer() (Line: 472)
Drupal\Core\DrupalKernel->boot() (Line: 707)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

[lando logs -s appserver.txt](https://github.com/lando/drupal/files/8164078/lando.logs.-s.appserver.txt)
