### ISSUE TITLE
The Drupal console doesn't appear to be installed on the Drupal 9 recipe

### ISSUE THREAD

**Issue by jcmartinez** [lando/drupal#18]
The Drupal console appear to be installed by default on the Drupal 8 recipe; however, it doesn't appear to be installed on the Drupal 9 recipe.

Could you add the Drupal console to the Drupal 9 recipe?

If not, could you document how to make it work on the Drupal 9 recipe?

**Comment by labboy0276** [comment]
Please check out this issue: https://github.com/lando/lando/issues/3044  Drupal console was basically unattended for a long time and was incompatible with D9, so we didnt include it initially and have no plans to add it in the future.
