### ISSUE TITLE
SSH known_hosts file is overwritten

### ISSUE THREAD

**Issue by bfuzze** [lando/drupal#19]
While using the Drupal 9 recipe, my known hosts file gets clobbered every time I restart.  I'm left with a broken symlink owned by root.  

![image](https://user-images.githubusercontent.com/1250453/162013244-27475e4a-5284-4caf-bd5f-b279fc043c5b.png)

I found a similar issue, but it is from a couple years ago and was unresolved: https://github.com/lando/lando/issues/2278

I have gone through my config and can not find anything custom that would be causing this, so I'm looking for ideas and/or work-arounds.

**Comment by AaronFeledy** [comment]
@bfuzze Did you ever get it working?

The `/user` directory is actually a mount pointing to the home directory on your host. So if that symlink is broken, then either docker couldn't mount your home directory or `~/.ssh/known_hosts` doesn't exist or can't be accessed.

Given that there have been no updates here for two years I'm going to assume this is resolved and close it out. Please let us know if it's still an issue.
