### ISSUE TITLE
macOS Lando installer does not validate arm64 / x64

### ISSUE THREAD

**Issue by daynis-olman** [lando/drupal#29]
Installed proceed to install the lando arm64 version on x64 resulting in bad CPU error on application start as below
`zsh: bad CPU type in executable: lando`

**Comment by reynoldsalec** [comment]
I believe now that we're moved over to script installers this is no longer an issue (arch detection is part of the posix script), so should be solved!

**Comment by kraptor** [comment]
Seems there is something not working yet, as it tries to pull the wrong image even while detecting the proper arch:
```
! database The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested           
```

I'm using `database: mysql:8.0`

**Comment by reynoldsalec** [comment]
@kraptor I think that's an issue with the `lando/mysql` service, which seems to be pinned to a version of MySQL 8.0 that doesn't have an arm image available. I've opened up a new issue for that: https://github.com/lando/mysql/issues/57

**Comment by daynis-olman** [comment]
Thanks @reynoldsalec 👍
