### ISSUE TITLE
Drupal 10 requires composer 2.3.6 or higher

### ISSUE THREAD

**Issue by gitressa** [lando/drupal#31]
[Drupal 10 requires composer 2.3.6 or higher](https://www.drupal.org/docs/system-requirements/composer-requirements) so perhaps Composer should get updated? See also https://github.com/lando/drupal-contributions/issues/69.

**Comment by StijnHaulotte** [comment]
Actualy i thionk it's also good fro drupal 9.0 to habe the default composer at least at 2.2 because of the allowed plugins

**Comment by reynoldsalec** [comment]
Guessing this may be even higher now; good issue for a contributor to check out! We should probably update the defaults in the PHP images we use, ex: https://github.com/lando/php/blob/main/images/8.1-fpm/Dockerfile#L73, although if we do this it would require us to revise a bunch of the tests across all our PHP-using recipes to check for that version of Composer, so it could be a bit of an undertaking.

**Comment by reynoldsalec** [comment]
Perhaps the best approach here is to use `2-latest` within the builder files for the Drupal recipe...it would be good to verify _how_ this is working now...strange that we didn't use `2-latest` right now.

**Comment by reynoldsalec** [comment]
I should ping @StephanieF on the Acquia issue coming out of this!
