### ISSUE TITLE
Inconvenient appserver locale 'POSIX'

### ISSUE THREAD

**Issue by drubb** [lando/drupal#41]
This might not be limited to Drupal recipes:

When entering the appserver container (lando ssh), or issuing Drush commands (lando drush) there's no supprt for special chars, e.g. German umlauts. The reason is, that the container's locale is set to POSIX:
```
www-data@ad5a078ae96d:/app$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
www-data@ad5a078ae96d:/app$
```
I'd expect to see a locale based on UTF-8, like en_US.UTF-8. Is this an issue with the upstream Bitnami images? And how can it be fixed?

**Comment by reynoldsalec** [comment]
I think OP is correct in assuming this is a bitnami issue: https://github.com/bitnami/minideb/issues/151

Going to close this out, we're planning on using offical Docker images for Lando 4, so likely this problem will be kicked to the defaults used by those services. It could make sense for Lando to set these values on boot, so I'll add a Lando 4 tag to this issue in case someone can reference it down the road.
