### ISSUE TITLE
Lando app urls appear on red on wifi connection

### ISSUE THREAD

**Issue by Lua19** [lando/drupal#52]
I have an issue when i start my application running the command "lando start" at home, as the example.lndo.site URLs appear on red and the project is not available to view in the browser, however, when i do the same using my company's internal ethernet connection the project launches without any issue

**Comment by reynoldsalec** [comment]
This is likely an issue with your home network configuration; see https://docs.lando.dev/help/dns-rebind.html for reference (and read https://docs.lando.dev/core/v3/proxy.html if you want all the gritty details on the *.lndo.site domain).
