### ISSUE TITLE
Lando 3.17.0 causes issue with json api module

### ISSUE THREAD

**Issue by vermario** [lando/drupal#56]
Hello!

The new 3.17.0 version of lando seems to have issues with the JSONAPI Drupal core module (Drupal 10, latest version).

### Symptom: 

Jsonapi responds with an error: 

`"The following query parameters violate the JSON:API spec: 'q'."`

![image](https://github.com/lando/drupal/assets/185412/1149bdb8-1cd0-49db-8fbb-ab4a99cc8a61)

### How to reproduce

You could reproduce this by: 

1. cloning this repository: https://github.com/wunderio/drupal-project (we use it at our company for all projects, it's been well tested)
2. make sure you have lando 3.17 installed
3. `lando start && lando drush si -y && lando drush en jsonapi -y` 
4. visit https://drupal-project.lndo.site/jsonapi and witness the error.

Now, remove 3.17.0, reinstall 3.11, lando destroy and repeat the operations above, and jsonapi  will work normally.

In another project of ours, where Drupal is installed in a subdirectory, we instead get a redirect loop at /jsonapi with 3.17.0, but all normal with 3.11.

This has been confirmed by a coworker with a different development machine.

I have found this issue in Drupal.org: https://www.drupal.org/project/jsonapi/issues/2984044 which refers to some configuration in nginx that jsonapi responds to by throwing this error. Was some default nginx configuration changed in this release?

Hope this helps!

**Comment by vermario** [comment]
I have tested this with the newly released 3.17.1, and the same error happens.

**Comment by reynoldsalec** [comment]
Could be a change in the NGINX config between 3.11 and 3.17...could be good to add a test to our Drupal suite once we fix this.

**Comment by reynoldsalec** [comment]
I'm going to replicate this on a stock `drupal10` recipe, and if I have the same issue, first try reverting this [NGINX config change](https://github.com/lando/drupal/compare/v0.7.0...main#diff-7589f23a0d379ddfef0cba81f82fefd789da73547ed1f5073f08eed5a42c73edR99), which appears to be the only one made between the relevant Drupal plugin versions.

**Comment by millnut** [comment]
Confirming it is related to that nginx change, just creating a PR now for it

**Comment by millnut** [comment]
Fixed in this PR https://github.com/lando/drupal/pull/57
