### ISSUE TITLE
Your PHP installation is too old. Refer to the [Drupal PHP requirements] - Vanilla Drupal 9 Recipe from Lando documentation

### ISSUE THREAD

**Issue by prodkt** [lando/drupal#63]
Your PHP installation is too old. Refer to the [Drupal PHP requirements](https://www.drupal.org/docs/system-requirements/php-requirements) for the currently recommended PHP version for this release. See [PHP's version support documentation](https://php.net/supported-versions.php) for more information on PHP's own support schedule.

Lando PHP container
![image](https://github.com/lando/lando/assets/101760605/1c4daa4a-e30e-421e-9655-03023da88145)

Not that this matters much, but just for coverage this is my local
![image](https://github.com/lando/lando/assets/101760605/9ebf7802-f5d1-4230-af00-c3df9dc8050d)

I used your Vanilla Drupal 9 recipe in the docs, and although I am on a non-supported version of docker, that doesn't appear to be the cause of issue here as an unsupported php version is being used by your recipe. 
![image](https://github.com/lando/lando/assets/101760605/b6344dbf-e189-406e-a8d3-c81f0cd101b7)

**Comment by AaronFeledy** [comment]
What does `lando ssh -c "php -v"` show?

**Comment by Stargate-project** [comment]
Stop using php 7.4 as the default for every PHP project. That is the problem.

**Comment by AaronFeledy** [comment]
The default should align with the product that you're running and the adoption level at hosting providers. The Drupal 9 recipe runs PHP 8.0 by default, which is supported by all versions of Drupal 9 and widely supported by hosting providers. Which version of Drupal are you running? Drupal 10 requires PHP 8.1, which is not installed by default on the Drupal 9 recipe.

**Comment by reynoldsalec** [comment]
Note that all the Drupal recipes _should_ be on the relevant PHP versions, if anyone experiences otherwise, make sure your Lando is up-to-date (run `lando update` on 3.21+ versions).
