### ISSUE TITLE
Drupal 7 recipe always returns 500

### ISSUE THREAD

**Issue by no-sssweat** [lando/drupal#64]
Using version 3.19.5 and 3.18.0 (I have not tested other older versions) Drupal 7 recipe fails to give 200 response.

![image](https://github.com/lando/lando/assets/50061027/d2f4aa39-60e2-41cb-ae4f-cacf0a0a59ad)

I have no issues with D9 or D10 recipes.

**Comment by reynoldsalec** [comment]
@no-sssweat you get any farther with this? Would be interested in what steps you took and any Landofile customizations you may have made...otherwise it may simply be an application error.

**Comment by peterhebert** [comment]
I am experiencing this same issue with Lando v3.21.0-beta.12.

**Comment by reynoldsalec** [comment]
@peterhebert likewise, have you confirmed it's not an application error/can you give me a copy of your Landofile? Thanks!

**Comment by peterhebert** [comment]
The landofile was working successfully for over a year before the latest Lando upgrade...

`name: sitename-d7
recipe: drupal7
config:
  webroot: .
  php: 7.4
services:
  phpma:
    type: phpmyadmin
    hosts:
      - database
  myruby:
    type: ruby:2.5.3
    build_as_root:
      - gem install compass
tooling:
  ruby:
    service: myruby
  compass:
    service: myruby
`

**Comment by peterhebert** [comment]
[lando.yml.txt](https://github.com/lando/drupal/files/14795912/lando.yml.txt)

**Comment by reynoldsalec** [comment]
That .lando.yml spins up ok for me @peterhebert. A few things to try:

- Make sure your plugins are up-to-date by running `lando update`
- Try a rebuild `lando rebuild -y`
- Check the error logs `lando logs` to see if you can find any specific errors
- Try starting the same project "from scratch" in a separate directory, changing the project name on the `.lando.yml` so you're starting from a brand new DB/etc.

**Comment by peterhebert** [comment]
I've already done these steps, as well as completely uninstalling and reinstalling Lando from scratch, including deleting the .lando directory in my home folder, even reinstalling the docker engine. still having the same issues, even worse now, as services on every site that I try to spin up are returning `✖ Request failed with status code 500` errors. This software is completely broken. I am extremely disappointed, as I rely on this for my work. I used to love this software, but now all the simplcity is gone, I am going to probably need to learn docker compose itself and move on from Lando.

**Comment by reynoldsalec** [comment]
Totally understand @peterhebert, LMK if you want to try debugging a bit more, happy to do a screenshare to see if we can find out what's going on, but know it's more time investment. You can reach me by DM on the Lando Slack (https://launchpass.com/devwithlando if you're not already on there, I'm `reynoldsalec` on there as well.

**Comment by jonasflint** [comment]
Have a bunch of Drupal 7 sites I’m trying to resurrect for archival purposes.  This happens on every single one of them…

**Comment by AaronFeledy** [comment]
This is almost always an application error such as when your Drupal 7 site requires php 7.2 but Lando uses 7.4 if you don't specify the version. Lando starts fine, but it's your site returning the 500 error. What do you see in the browser or with `lando drush ws`?
