### ISSUE TITLE
lando error

### ISSUE THREAD

**Issue by purnima-kumar** [lando/drupal#69]
Upon lando start, I get this error- ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1
I do have that container in my docker desktop. ANyone has an idea about it?

**Comment by AaronFeledy** [comment]
You likely need to update Lando. Please see lando/core-next#46

**Comment by reynoldsalec** [comment]
@purnima-kumar definitely re-open this or go on the [Lando Slack](https://launchpass.com/devwithlando) if you have further questions, thanks @AaronFeledy for following up here!
