### ISSUE TITLE
Problem with Drupal s3fs module

### ISSUE THREAD

**Issue by CDTdenisP** [lando/drupal#82]
Hi, I have encountered a problem using this module on Drupal https://www.drupal.org/project/s3fs.

It seems to be missing some requirements for the module to work properly.

https://www.drupal.org/project/s3fs/issues/3413499#comment-15390486

**Comment by reynoldsalec** [comment]
Based on the requirements listed on the project's page, (`allow_url_fopen = On` in php.ini and the `curl` extension being loaded) I don't think there should be an out-of-the-box issue.

The [linked issue](https://www.drupal.org/project/s3fs/issues/2974302#comment-14509096) does sound like it might be relevant, in which case you may need to provide some custom nginx config (see https://docs.lando.dev/plugins/drupal/config.html#using-custom-config-files)

@CDTdenisP you ever figure this out in your config?

**Comment by reynoldsalec** [comment]
Going to close this out, but would be curious if @CDTdenisP if you ever found a workable solution/got to follow that thread that I sent.
