### ISSUE TITLE
Step paused on "Lando drush site:install ..."

### ISSUE THREAD

**Issue by vimmacs** [lando/drupal#94]
Hello.

Following Lando Official Guide Steps, we went to this step and the issue occured:
**=>**`lando drush site:install --db-url=mysql://drupal10:drupal10@database/drupal10 -y` 
**=>**`[preflight] Package "drupal/core" is not installed`

This is an unexpected output.

Environment:
1. Latest Lando with its built-in Docker // v3.21.0-beta.1
2. Macbook M1Pro Chip; project folder "b6". please refer to the attachment. 
<img width="1121" alt="Screenshot 2024-02-19 at 18 46 32" src="https://github.com/lando/lando/assets/66717650/31d7ee16-9f63-46cd-b17a-8d0c33929fa7">

**Comment by reynoldsalec** [comment]
Tried replicating this on my (also M1 Mac) laptop and wasn't having success; as long as you run the `lando composer create-project drupal/recommended-project:10.0.x-dev@dev tmp && cp -r tmp/. . && rm -rf tmp` command, you should have `drupal/core` installed prior to running `lando start`.

If you're getting stuck on this, you might try running `lando start` and then running `lando composer create-project drupal/recommended-project:10.0.x-dev@dev tmp && cp -r tmp/. . && rm -rf tmp`...I think both are equivalent.

Definitely re-open this or [ping me on Slack](https://www.launchpass.com/devwithlando) if you have more questions!

**Comment by vimmacs** [comment]
Thanks for your detailed guidance @reynoldsalec . The rm -rf tmp approached worked!
