### ISSUE TITLE
Drupal 6 test suite fails on `drush si`

### ISSUE THREAD

**Issue by reynoldsalec** [lando/drupal#98]
The following fails, both when I try it with our example app and in the test suite:

`lando drush si --db-url=mysql://drupal6:drupal6@database/drupal6 -y`

...producing the error `PHP Fatal error:  Call to undefined function db_result() in phar:///usr/local/bin/drush/commands/core/drupal/site_install_6.inc on line 145` 

Presumably this means that `drush si` doesn't work with Drupal 6, at least in our context. I do know that others have had significant issues with this in the past, so it's very possible that there isn't really a great solution for using `drush si` with Drupal 6 any more. That's one reason I didn't pursue this further, but would be great to get other eyes on it :)

**Comment by millnut** [comment]
Hi @reynoldsalec do you get the same error with using `mysqli` instead?

```bash
lando drush si --db-url=mysqli://drupal6:drupal6@database/drupal6 -y
```

**Comment by reynoldsalec** [comment]
I do @millnut, although if you're able to get it working would love to hear how.

Overall, I think Jeff Geerling's comment on this thread sums up my feelings: https://github.com/drush-ops/drush/issues/218#issuecomment-387912746
